# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47dcce7548011c9c471e0705f5ec1866dba2c717cd24594ea2a94c67ffbb3cbb125567ef708016787f6c26d1c255641f73b072202a93306bd94f90b699acbac9

test:
  secret_key_base: 547db0b9fe25fe37082f48bcce0f28fcabe4e7a20f4abc6f1a4764ad85b78e71c061b462b165259df3ba9c32c4649b6d2603ea91ab5ad32f0012cdeb8ef0b930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
